1 Exercises
1.0.1 numpy arrays

For each of the next 10 exercises, create a new code cell and write your solution.

1. Import the numpy library with the standard namespace

In [2]:
import numpy as np

2. Create an array, a, with the numbers from 0 to 6.

In [3]:
list1 = [0,1,2,3,4,5,6]
a = np.array(list1)
print(a)

[0 1 2 3 4 5 6]


3. Create another array, b, with all even numbers from 50 to 60 (included).

In [4]:
b = np.arange(50,61,2)
print(b)

    

[50 52 54 56 58 60]


4. Create an array of length 10 with the squares of the first natural numbers, that is 1,4,9,…

In [11]:
c = np.arange(1,11,1)
print(c*c)

[  1   4   9  16  25  36  49  64  81 100]


5. Create an array of 200 elements in which the fist 100 elements are ones; and the last 100
elements are zeros

In [14]:
myones = np.ones(100)
myzeroes = np.zeros(100)

print(myones, myzeroes)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.] [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


6. You have two lists of numbers that are supposed to be identical (imagine that there are
thousands of elements). How could you check if the two lists are identical using numpy, and
count the number of different elements if any?

In [15]:
list1 = [1, 2, 3, 4, 5]
list2 = [1, 2, 3, 4, 5]
array1 = np.array(list1)
array2 = np.array(list2)
array1==array2

array([ True,  True,  True,  True,  True])