In [3]:
import pandas as pd
import numpy as np

#data_ord=pd.read_excel('data_lecture3.xlsx', sheet_name='data3')
data_cat=pd.read_excel('3.1_data_session 3.xlsx', sheet_name='data4')


In [4]:
data_cat

Values
0           Lee
1        Leslie
2          John
3     Guadalupe
4          John
...         ...
4583      James
4584     Leslie
4585     Robert
4586     Jessie
4587        Lee

[4588 rows x 1 columns]

We create a function that gets a list/array as input, and produce a frequency table.
There are many ways. For instance:

In [17]:
list_values = data_cat['Values']
elements=list(set(list_values))
elements
freq=[(name, sum(list_values==name)) for name in elements]
freq

[('William', 237),
 ('Willie', 222),
 ('Leslie', 247),
 ('James', 239),
 ('Francis', 229),
 ('Marion', 223),
 ('Charles', 222),
 ('Billie', 213),
 ('Joseph', 215),
 ('Mary', 222),
 ('Robert', 235),
 ('Joe', 210),
 ('Dana', 223),
 ('Guadalupe', 244),
 ('Jean', 244),
 ('Carmen', 211),
 ('Johnnie', 216),
 ('Lee', 240),
 ('John', 238),
 ('Jessie', 258)]

But this can be easily done using pandas:

In [19]:
freq2=data_cat['Values'].value_counts()
freq2

Jessie       258
Leslie       247
Guadalupe    244
Jean         244
Lee          240
James        239
John         238
William      237
Robert       235
Francis      229
Marion       223
Dana         223
Mary         222
Willie       222
Charles      222
Johnnie      216
Joseph       215
Billie       213
Carmen       211
Joe          210
Name: Values, dtype: int64

For continuous data is also simple, using numpy:

In [21]:
data_cont=pd.read_excel('data_lecture3.xlsx', sheet_name='data1')
data_cont.describe()

Values
count  5038.000000
mean      0.005716
std       0.995407
min      -3.653974
25%      -0.669343
50%       0.035281
75%       0.680483
max       3.186374

Let's make 30 equally spaces bins or ranges:

In [22]:
my_hist = np.histogram(data_cont, 30)
my_hist

(array([  1,   2,   7,   5,  11,  31,  40,  76, 115, 144, 195, 288, 311,
        395, 393, 426, 459, 440, 432, 366, 253, 232, 148, 108,  73,  34,
         26,  14,   8,   5], dtype=int64),
 array([-3.65397368, -3.4259621 , -3.19795052, -2.96993894, -2.74192736,
        -2.51391578, -2.2859042 , -2.05789262, -1.82988104, -1.60186946,
        -1.37385788, -1.1458463 , -0.91783472, -0.68982314, -0.46181156,
        -0.23379998, -0.0057884 ,  0.22222318,  0.45023476,  0.67824634,
         0.90625792,  1.1342695 ,  1.36228108,  1.59029266,  1.81830424,
         2.04631582,  2.2743274 ,  2.50233898,  2.73035056,  2.95836214,
         3.18637372]))

The first array are the frequency values.
The second array are the limits of the bin (All but the last (right hand-most) bin is half-open.)


In [23]:
my_hist[0]

array([  1,   2,   7,   5,  11,  31,  40,  76, 115, 144, 195, 288, 311,
       395, 393, 426, 459, 440, 432, 366, 253, 232, 148, 108,  73,  34,
        26,  14,   8,   5], dtype=int64)

In the next video, we will learn how to plot all these frequency tables using bar charts and histograms.