1 Exercises

1.0.1 for loops

For each of the next exercises, create a new code cell and write your solution

1. let v=['a', 'g', 'k', 'm'] be a list. Make a for loop that prints each of the elements of
the list

In [4]:
v = ['a','g','k','m']
for i in v:
   print(i)

a
g
k
m


2. Make a for loop that goes from the element 6 to the element 30 (included) and add all the
elements, then print the result

In [21]:
result = 0
for i in range(6,31,1):
    result = result+i
print("sum of all element from 1 to 61 is " , result)

sum of all element from 1 to 61 is  450


3. Using a for loop, sum all the numbers from 1 to 1 million. Then print the result

In [25]:
result2 = 0
for i in range(1,10000001):
     result2 = result2+i
print(result2)

50000005000000


4. Using a for loop, find the factorial of 10. That is, ‘10!=1098765432*1’

In [29]:
x = 1
for i in range(1,11):
    x = x*i
print("The factorial of 10! is " , x)


The factorial of 10! is  3628800


5.Create a 2 dimensional numpy array Mul[i,j] of size 10x10, use loops to fill the array with
the multipliction table. That is, the element Mul[4,7] for instance must be equal to 4x7=28

In [32]:
import numpy as np
array1 = np.arange(1,11,1)
array2 = np.arange(1,11,1)
array1,array2

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

6. You have two lists of equal length. one with first names, and one with family names. For
instance names=['John', 'Emily', ...], f_names=['Adams', 'Blunt',...]. Use loops
to print the i-th name and the i-th family name at each iteration. That is > John Adams,
Emily Blunt, …

In [77]:

names = ['Emmanuel','Jennifer', 'Kate']
f_names = ['Kant', 'Anniston','Winslet']

# Iterate over the range of indices directly
for i in range(len(names)):
    print(names[i], f_names[i])


Emmanuel Kant
Jennifer Anniston
Kate Winslet


7.You have two numpy arrays of the same length with numbers, for instance v=[8,3,6,0] and
w=[3,-1,8,2]. Compute a third array with the in which each element i of the new array
is the product of the element i of array 1 and the element N-i of array 2. That is, in this
example, [8x2,3x8,6x(-1),0x3] that is [16,24,-6,0]

In [78]:
import numpy as np

# Define the arrays
v = np.array([8, 3, 6, 0])
w = np.array([3, -1, 8, 2])

# Compute the third array using element-wise multiplication and reversing one of the arrays
result = v * w[::-1]

print(result)


[16 24 -6  0]


Using loops, compute the sum all multiples of three from 3 up to 600 (included)

In [81]:
x = 0
for i in range(3,601,3):
    x = x+i
print("The sum of all multiples of three from 3 to 600 is:", x)

The sum of all multiples of three from 3 to 600 is: 60300


In [4]:
cumulative = 0
for i in range(2,10):
    x = i**2
    cumulative = cumulative + x
    print(i,x,cumulative)

2 4 4
3 9 13
4 16 29
5 25 54
6 36 90
7 49 139
8 64 203
9 81 284
